version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: arizona-plants-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - arizona-plants-network
    # Simplified health check
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:6333/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arizona-plants-api
    ports:
      - "8000:8000"
    volumes:
      - model_cache:/root/.cache/huggingface
      - model_cache_torch:/root/.cache/torch
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - COLLECTION_NAME=arizona_plants
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - HF_HOME=/root/.cache/huggingface
    depends_on:
      - qdrant  # Simple depends_on without health check
    networks:
      - arizona-plants-network

networks:
  arizona-plants-network:
    driver: bridge

volumes:
  qdrant_storage:
    driver: local
  model_cache:
    driver: local
  model_cache_torch:
    driver: local